import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Foundation service for Firebase infrastructure.
///
/// Centralizes initialization and status checking for Firebase services.
/// Does not implement authentication, Firestore CRUD, or cloud favorites
/// at this milestone.
class FirebaseService {
  FirebaseService._();

  static bool _isInitialized = false;

  /// Whether Firebase was successfully initialized.
  static bool get isInitialized => _isInitialized;

  /// Initializes the default Firebase application.
  ///
  /// Accepts optional [FirebaseOptions] for platforms (such as Web) that
  /// require explicit configuration when generated by FlutterFire.
  ///
  /// If configuration options are absent or initialization fails, errors
  /// are logged with full details rather than swallowed silently, allowing
  /// the app to start up and run reliably in local/in-memory mode.
  static Future<void> initialize({FirebaseOptions? options}) async {
    try {
      if (Firebase.apps.isEmpty) {
        if (options != null) {
          await Firebase.initializeApp(options: options);
        } else {
          await Firebase.initializeApp();
        }
      }
      _isInitialized = true;
      debugPrint('[FirebaseService] Firebase initialized successfully.');
    } catch (e, stackTrace) {
      _isInitialized = false;
      debugPrint('[FirebaseService] Firebase initialization notice: $e');
      debugPrint('[FirebaseService] StackTrace: $stackTrace');
    }
  }

  /// Reset internal state (primarily used for unit testing).
  @visibleForTesting
  static void resetForTesting() {
    _isInitialized = false;
  }
}
