// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoC46Ko8smJhMWafVg6qp1-2Cp0gxYCR8',
    appId: '1:849573187732:web:96a91a153016f3c0dba481',
    messagingSenderId: '849573187732',
    projectId: 'recipe-app-flutter-ed984',
    authDomain: 'recipe-app-flutter-ed984.firebaseapp.com',
    storageBucket: 'recipe-app-flutter-ed984.firebasestorage.app',
    measurementId: 'G-0BTVFD80D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPj3C22cO49emrK9NiVDikxMwmvACAQj8',
    appId: '1:849573187732:android:15a5b789a1b11297dba481',
    messagingSenderId: '849573187732',
    projectId: 'recipe-app-flutter-ed984',
    storageBucket: 'recipe-app-flutter-ed984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJf77SlYgnqNSjZLHPDwei3s89a0FjZQ',
    appId: '1:849573187732:ios:e108f771275cf8e9dba481',
    messagingSenderId: '849573187732',
    projectId: 'recipe-app-flutter-ed984',
    storageBucket: 'recipe-app-flutter-ed984.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
